skinparam useBetaStyle true
skinparam shadowing false
<style>
mindmapDiagram {
  RoundCorner 24
  FontColor #fff
  node {
    BackGroundColor #3A86FF
    LineColor #3A86FF80
  }
  :depth(0) {
    BackGroundColor #FFBE0B
    LineColor #FFBE0B80
  }
  :depth(1) {
    BackGroundColor #FB5607
    LineColor #FB560780
  }
  :depth(2) {
    BackGroundColor #FF006E
    LineColor #FF006E80
  }
  :depth(3) {
    BackGroundColor #8338EC
    LineColor #8338EC80
  }
  :depth(4) {
    BackGroundColor #3A86FF
    LineColor #3A86FF80
  }
}
</style>
